### ISSUE TITLE
Update .travis.yml

### ISSUE THREAD

**Issue by stramel** [PolymerLabs/tedium#57]
Purposed Changes:
- Travis has pushed a shorthand for installing chrome `chrome: stable` like how firefox is handled.
- Override the `install` phase to have the install commands
    - Use `polymer install --variants` to install any variants
- Add `polymer lint` to the `before_scripts`
- Add a `polymer.json` for the linter.
- Run in containerized environment (`sudo: false`)
- Update test command to run variants, `polymer test` will run all variants in all browsers
    - use `polymer test` instead of `polymer test -l chrome` and `polymer test -l firefox`
- Could also incorporate the `node_modules` caching into this if you want as well.

I am more than willing to put out a PR if you guys are good with these changes.

purposed `.travis.yml`

```yml
language: node_js
sudo: false
before_script:
  - polymer lint
install:
  - npm install -g polymer-cli
  - polymer install --variants
env:
  global:
    - secure: >-
        INSERT_KEY
    - secure: >-
        INSERT_KEY
node_js: stable
addons:
  firefox: latest
  chrome: stable
  sauce_connect: true
script:
  - xvfb-run polymer test
  - >-
    if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then polymer test -s 'default';
    fi
dist: trusty
```
